"""CompiledDrawing + HLR lines -> DXF (ezdxf, MIT). The sheet is drawn 1:1 in millimetres.

Dimension texts are the GeometryIR values carried by the compiled drawing (explicit text
override), never the measured sheet distance.
"""

from __future__ import annotations

import math

import ezdxf
from ezdxf.enums import TextEntityAlignment

from drawing_schema.compiled import AnnotationKind, CompiledDrawing, DimensionOp, DimensionOpKind

LAYERS = {
    # name: (linetype, lineweight in 1/100 mm, ACI colour)
    "SHEET": ("Continuous", 13, 8),
    "FRAME": ("Continuous", 50, 7),
    "TITLE": ("Continuous", 25, 7),
    "VISIBLE": ("Continuous", 50, 7),
    "HIDDEN": ("DASHED", 25, 8),
    "CENTER": ("CENTER", 18, 1),
    "DIM": ("Continuous", 18, 5),
    "NOTES": ("Continuous", 18, 7),
}
GENERATOR_NOTE = (
    "GENERATED BY CAD DRAWING AI - OPEN-SOURCE OCCT/EZDXF EXECUTOR. NOT PRODUCED BY SOLIDWORKS."
)


def _setup(doc) -> None:
    doc.units = 4  # millimetres
    doc.header["$MEASUREMENT"] = 1
    doc.header["$INSUNITS"] = 4
    doc.header["$LTSCALE"] = 8.0
    for name, (lt, lw, color) in LAYERS.items():
        doc.layers.add(name, linetype=lt, lineweight=lw, color=color)
    ds = doc.dimstyles.get("EZDXF")
    ds.dxf.dimtxt = 3.5
    ds.dxf.dimasz = 3.0
    ds.dxf.dimexe = 2.0
    ds.dxf.dimexo = 1.0
    ds.dxf.dimgap = 1.0
    ds.dxf.dimtad = 1
    ds.dxf.dimclrd = 256
    ds.dxf.dimclre = 256
    ds.dxf.dimclrt = 256


def _arrow(msp, tip, tail, size=3.0, layer="DIM") -> None:
    dx, dy = tip[0] - tail[0], tip[1] - tail[1]
    n = math.hypot(dx, dy) or 1.0
    ux, uy = dx / n, dy / n
    bx, by = tip[0] - ux * size, tip[1] - uy * size
    w = size / 6
    msp.add_solid([tip, (bx - uy * w, by + ux * w), (bx + uy * w, by - ux * w)], dxfattribs={"layer": layer})


def _text(msp, text, at, height, layer="NOTES", align=TextEntityAlignment.LEFT, rotation=0.0) -> None:
    lines = text.split("\n")
    for k, line in enumerate(lines):
        y = at[1] - k * height * 1.6
        msp.add_text(line, height=height, rotation=rotation, dxfattribs={"layer": layer}).set_placement(
            (at[0], y), align=align
        )


def _linear(msp, d: DimensionOp, p1, p2) -> None:
    if d.horizontal:
        base = ((p1[0] + p2[0]) / 2, d.line_at)
        angle = 0
    else:
        base = (d.line_at, (p1[1] + p2[1]) / 2)
        angle = 90
    dim = msp.add_linear_dim(base=base, p1=p1, p2=p2, angle=angle, text=d.text, dimstyle="EZDXF",
                             dxfattribs={"layer": "DIM"})
    dim.render()


def _leader(msp, d: DimensionOp) -> None:
    tip, land = d.leader[0], d.leader[1]
    msp.add_line(tip, land, dxfattribs={"layer": "DIM"})
    _arrow(msp, tip, land)
    _text(msp, d.text, (d.text_at[0], d.text_at[1] - d.text_height / 2), d.text_height, layer="DIM",
          align=TextEntityAlignment.LEFT)


def _title_block(msp, cd: CompiledDrawing, generator: str) -> None:
    tb = cd.title_block
    msp.add_lwpolyline([(tb.x0, tb.y0), (tb.x1, tb.y0), (tb.x1, tb.y1), (tb.x0, tb.y1)], close=True,
                       dxfattribs={"layer": "FRAME"})
    cols, rows = 4, 4
    cw, rh = tb.w / cols, tb.h / rows
    for c in range(1, cols):
        msp.add_line((tb.x0 + c * cw, tb.y0), (tb.x0 + c * cw, tb.y1), dxfattribs={"layer": "TITLE"})
    for r in range(1, rows):
        msp.add_line((tb.x0, tb.y0 + r * rh), (tb.x1, tb.y0 + r * rh), dxfattribs={"layer": "TITLE"})
    max_chars = int((cw - 2) / (2.5 * 0.62))
    for k, f in enumerate(cd.title_fields[: cols * rows]):
        r, c = divmod(k, cols)
        x = tb.x0 + c * cw + 1.5
        y_top = tb.y1 - r * rh
        _text(msp, f.label, (x, y_top - 2.8), 1.8, layer="TITLE")
        value = f.value if len(f.value) <= max_chars else f.value[: max_chars - 1] + "…"
        _text(msp, value, (x, y_top - 7.5), 2.5, layer="TITLE")


def _notes(msp, cd: CompiledDrawing, generator: str) -> None:
    x = cd.frame.x0 + 4.0
    y = cd.title_block.y1 - 5.0
    lines = [
        f"{cd.drawing_kind.value} DRAWING - ALL DIMENSIONS IN mm, TAKEN FROM THE CAD GEOMETRY.",
        "MATERIAL, TOLERANCES, GD&T, DATUMS AND SURFACE FINISH ARE NOT SPECIFIED UNLESS STATED IN THE TITLE BLOCK.",
        GENERATOR_NOTE,
        f"EXECUTOR: {generator}",
    ] + [f"NOTE: {n}" for n in cd.notes[:3]]
    max_chars = int((cd.title_block.x0 - x - 4.0) / (2.2 * 0.62))
    for line in lines:
        if y < cd.frame.y0 + 3:
            break
        _text(msp, line if len(line) <= max_chars else line[: max_chars - 1] + "…", (x, y), 2.2)
        y -= 4.0


def write_dxf(cd: CompiledDrawing, sheet_lines: dict[str, dict], snapped: dict[str, tuple], path,
              generator: str) -> None:
    """sheet_lines: view id -> {"visible": [...], "hidden": [...]} in sheet mm.
    snapped: dimension id -> (p1, p2) extension origins after snapping."""
    doc = ezdxf.new("R2018", setup=True)
    _setup(doc)
    msp = doc.modelspace()
    msp.add_lwpolyline([(0, 0), (cd.sheet_w, 0), (cd.sheet_w, cd.sheet_h), (0, cd.sheet_h)], close=True,
                       dxfattribs={"layer": "SHEET"})
    f = cd.frame
    msp.add_lwpolyline([(f.x0, f.y0), (f.x1, f.y0), (f.x1, f.y1), (f.x0, f.y1)], close=True,
                       dxfattribs={"layer": "FRAME"})
    for view in cd.views:
        lines = sheet_lines[view.id]
        for layer in ("hidden", "visible"):
            for pl in lines[layer]:
                if len(pl) == 2:
                    msp.add_line(pl[0], pl[1], dxfattribs={"layer": layer.upper()})
                else:
                    msp.add_lwpolyline(pl, dxfattribs={"layer": layer.upper()})
        if view.label:
            drawn = [p for pl in lines["visible"] for p in pl]
            x0 = min((p[0] for p in drawn), default=view.outline.x0)
            y0 = min((p[1] for p in drawn), default=view.outline.y0)
            _text(msp, view.label, (x0, y0 - 6.0), 2.5)
    for a in cd.annotations:
        if a.kind == AnnotationKind.PITCH_CIRCLE:
            msp.add_circle(a.center, a.radius, dxfattribs={"layer": "CENTER"})
        elif a.kind == AnnotationKind.CENTER_MARK:
            p = a.points
            msp.add_line(p[0], p[1], dxfattribs={"layer": "CENTER"})
            msp.add_line(p[2], p[3], dxfattribs={"layer": "CENTER"})
        else:
            msp.add_line(a.points[0], a.points[1], dxfattribs={"layer": "CENTER"})
    for d in cd.dimensions:
        if d.kind == DimensionOpKind.LINEAR:
            p1, p2 = snapped.get(d.id, (d.p1, d.p2))
            _linear(msp, d, p1, p2)
        else:
            _leader(msp, d)
    _title_block(msp, cd, generator)
    _notes(msp, cd, generator)
    doc.saveas(str(path))
