"""CompiledDrawing + HLR lines -> DXF (ezdxf, MIT). The sheet is drawn 1:1 in millimetres.

Sheet format follows the SolidWorks standard templates used as references: ISO 5457 zone grid
(columns numbered right-to-left, rows lettered bottom-to-top), 180 x 55 mm title block with
the NAME / SIGNATURE / DATE sign-off table, a numbered "Note:" block above it, an optional
revision table top-right and a first/third-angle projection symbol.

Dimension texts are the GeometryIR values carried by the compiled drawing (explicit text
override), never the measured sheet distance. GD&T frames, datum feature symbols and surface
texture symbols are drawn as vector graphics from user-supplied data only.
"""

from __future__ import annotations

import math
import re
from functools import lru_cache

import ezdxf
from ezdxf.enums import TextEntityAlignment
from ezdxf.fonts import fonts

from drawing_schema.compiled import (
    AnnotationKind,
    CompiledDrawing,
    DimensionOp,
    DimensionOpKind,
    FrameSpec,
    PmiKind,
    PmiOp,
    Rect,
    ToleranceText,
)

FONT = "LiberationSans-Regular.ttf"  # Arial-metric sans (SIL OFL); ezdxf falls back if absent
STYLE = "CADAI"
TEXT_H = 3.5
TOL_H = 2.5
ARROW = 3.0
LAYERS = {
    # name: (linetype, lineweight in 1/100 mm). All drawn black (ACI 7) on white paper.
    "SHEET": ("Continuous", 13),
    "FRAME": ("Continuous", 50),
    "ZONES": ("Continuous", 25),
    "TITLE": ("Continuous", 25),
    "SHADE": ("Continuous", 0),
    "VISIBLE": ("Continuous", 50),
    "HIDDEN": ("DASHED", 25),
    "CENTER": ("CENTER", 18),
    "DIM": ("Continuous", 18),
    "GDT": ("Continuous", 25),
    "NOTES": ("Continuous", 25),
}
PROVENANCE = "GENERATED BY CAD DRAWING AI (OPEN-SOURCE OCCT HLR + EZDXF). NOT PRODUCED BY SOLIDWORKS."
_ALIGN = {"L": TextEntityAlignment.LEFT, "C": TextEntityAlignment.CENTER, "R": TextEntityAlignment.RIGHT,
          "MC": TextEntityAlignment.MIDDLE_CENTER, "ML": TextEntityAlignment.MIDDLE_LEFT}


# ---------------------------------------------------------------------------- primitives

@lru_cache(maxsize=64)
def _font(h: float):
    return fonts.make_font(FONT, h)


def text_w(text: str, h: float) -> float:
    return _font(round(h, 3)).text_width(text) if text else 0.0


def _setup(doc) -> None:
    doc.units = 4  # millimetres
    doc.header["$MEASUREMENT"] = 1
    doc.header["$INSUNITS"] = 4
    doc.header["$LTSCALE"] = 8.0
    doc.styles.add(STYLE, font=FONT)
    for name, (lt, lw) in LAYERS.items():
        doc.layers.add(name, linetype=lt, lineweight=lw, color=7)
    ds = doc.dimstyles.get("EZDXF")
    ds.dxf.dimtxt = TEXT_H
    ds.dxf.dimtxsty = STYLE
    ds.dxf.dimblk = ""  # closed filled arrowheads (ISO 129-1)
    ds.dxf.dimtsz = 0.0
    ds.dxf.dimasz = ARROW
    ds.dxf.dimexe = 2.0
    ds.dxf.dimexo = 1.0
    ds.dxf.dimgap = 1.0
    ds.dxf.dimtad = 1
    ds.dxf.dimlfac = 1.0
    ds.dxf.dimclrd = 256
    ds.dxf.dimclre = 256
    ds.dxf.dimclrt = 256


def _line(msp, a, b, layer="DIM") -> None:
    msp.add_line(a, b, dxfattribs={"layer": layer})


def _rect(msp, r: Rect, layer: str) -> None:
    msp.add_lwpolyline([(r.x0, r.y0), (r.x1, r.y0), (r.x1, r.y1), (r.x0, r.y1)], close=True,
                       dxfattribs={"layer": layer})


def _text(msp, text: str, at, h: float, layer="NOTES", align="L", rotation=0.0) -> None:
    for k, line in enumerate(text.split("\n")):
        dx = math.sin(math.radians(rotation)) * k * h * 1.6
        dy = -math.cos(math.radians(rotation)) * k * h * 1.6
        msp.add_text(line, height=h, rotation=rotation, dxfattribs={"layer": layer, "style": STYLE}).set_placement(
            (at[0] + dx, at[1] + dy), align=_ALIGN[align])


def _fit(text: str, width: float, h: float, h_min: float = 1.2) -> tuple[str, float]:
    """Shrink text to fit a cell; truncate only below h_min."""
    w = text_w(text, h)
    if w <= width or not text:
        return text, h
    h2 = h * width / w
    if h2 >= h_min:
        return text, h2
    while text and text_w(text + "…", h_min) > width:
        text = text[:-1]
    return text + "…", h_min


def _arrow(msp, tip, tail, size=ARROW, layer="DIM") -> None:
    dx, dy = tip[0] - tail[0], tip[1] - tail[1]
    n = math.hypot(dx, dy) or 1.0
    ux, uy = dx / n, dy / n
    bx, by = tip[0] - ux * size, tip[1] - uy * size
    w = size * math.tan(math.radians(15))
    msp.add_solid([tip, (bx - uy * w, by + ux * w), (bx + uy * w, by - ux * w)], dxfattribs={"layer": layer})


def _triangle(msp, base, toward, layer="GDT", h=3.0) -> tuple[float, float]:
    """Filled datum triangle: base centred on ``base`` (on the feature), apex toward ``toward``."""
    dx, dy = toward[0] - base[0], toward[1] - base[1]
    n = math.hypot(dx, dy) or 1.0
    ux, uy = dx / n, dy / n
    w = h / math.sqrt(3)  # equilateral
    apex = (base[0] + ux * h, base[1] + uy * h)
    msp.add_solid([(base[0] - uy * w, base[1] + ux * w), (base[0] + uy * w, base[1] - ux * w), apex],
                  dxfattribs={"layer": layer})
    return apex


def _circled(msp, letter: str, cx: float, cy: float, layer="GDT", r=1.7) -> None:
    msp.add_circle((cx, cy), r, dxfattribs={"layer": layer})
    _text(msp, letter, (cx, cy), 2.0, layer, "MC")


def _stadium(msp, x0, y0, x1, y1, layer="DIM", rotation=0.0, origin=(0.0, 0.0)) -> None:
    """Inspection-dimension oval around a label box given in label coordinates."""
    r = (y1 - y0) / 2
    pts = []
    for k in range(13):
        a = math.pi / 2 + math.pi * k / 12
        pts.append((x0 + r + r * math.cos(a), y0 + r + r * math.sin(a)))
    for k in range(13):
        a = -math.pi / 2 + math.pi * k / 12
        pts.append((x1 - r + r * math.cos(a), y0 + r + r * math.sin(a)))
    c, s = math.cos(math.radians(rotation)), math.sin(math.radians(rotation))
    pts = [(origin[0] + x * c - y * s, origin[1] + x * s + y * c) for x, y in pts]
    msp.add_lwpolyline(pts, close=True, dxfattribs={"layer": layer})


# ---------------------------------------------------------------------------- dimension labels

Piece = tuple[str, float, float, float]  # text, u, v (baseline), height


def _tol_pieces(tol: ToleranceText, u: float) -> tuple[list[Piece], float]:
    if tol.kind == "SYMMETRIC":
        return [(tol.upper, u + 0.8, 0.0, TEXT_H)], 0.8 + text_w(tol.upper, TEXT_H)
    w = max(text_w(tol.upper, TOL_H), text_w(tol.lower, TOL_H))
    gap = 0.8 if tol.kind == "DEVIATION" else 0.0
    return [(tol.upper, u + gap, TOL_H + 0.5, TOL_H), (tol.lower, u + gap, 0.0, TOL_H)], gap + w


def label_pieces(text: str, tol: ToleranceText | None) -> tuple[list[Piece], float, float]:
    """Single-line label (value [+ tolerance]) laid out along its baseline: pieces, width, height."""
    if tol is not None and tol.kind == "LIMITS":
        pieces, w = _tol_pieces(tol, 0.0)
        return pieces, w, 2 * TOL_H + 0.5
    pieces = [(text, 0.0, 0.0, TEXT_H)]
    w = text_w(text, TEXT_H)
    h = TEXT_H
    if tol is not None:
        tp, tw = _tol_pieces(tol, w)
        pieces += tp
        w += tw
        h = TEXT_H if tol.kind == "SYMMETRIC" else 2 * TOL_H + 0.5
    return pieces, w, h


def _place(msp, pieces: list[Piece], origin, rotation: float, layer="DIM") -> None:
    c, s = math.cos(math.radians(rotation)), math.sin(math.radians(rotation))
    for text, u, v, h in pieces:
        if text:
            msp.add_text(text, height=h, rotation=rotation, dxfattribs={"layer": layer, "style": STYLE}).set_placement(
                (origin[0] + u * c - v * s, origin[1] + u * s + v * c), align=TextEntityAlignment.LEFT)


def _linear(msp, d: DimensionOp, p1, p2) -> None:
    if d.horizontal:
        base, angle = ((p1[0] + p2[0]) / 2, d.line_at), 0
    else:
        base, angle = (d.line_at, (p1[1] + p2[1]) / 2), 90
    custom = d.tolerance is not None or d.inspection
    # a DIMENSION entity keeps the drawing editable in CAD; a toleranced / inspection label is drawn
    # explicitly (text " " suppresses the entity's own text)
    dim = msp.add_linear_dim(base=base, p1=p1, p2=p2, angle=angle, text=" " if custom else d.text,
                             dimstyle="EZDXF", dxfattribs={"layer": "DIM"})
    dim.render()
    b = d.text_bbox
    if not custom:
        return
    if dim.dimension.dxf.get("text_midpoint") is None:  # suppressed text: ezdxf leaves it unset
        dim.dimension.dxf.text_midpoint = ((b.x0 + b.x1) / 2, (b.y0 + b.y1) / 2, 0.0)
    pieces, w, h = label_pieces(d.text, d.tolerance)
    if d.horizontal:
        origin, rot = ((b.x0 + b.x1) / 2 - w / 2, b.y0), 0.0
    else:
        origin, rot = (b.x1, (b.y0 + b.y1) / 2 - w / 2), 90.0
    _place(msp, pieces, origin, rot)
    if d.inspection:
        _stadium(msp, -1.5, -1.0, w + 1.5, h + 1.0, rotation=rot, origin=origin)


_VALUE = [re.compile(r"Ø\d+(?:\.\d+)?"), re.compile(r"R\d+(?:\.\d+)?")]


def _leader(msp, d: DimensionOp) -> None:
    tip, land = d.leader[0], d.leader[1]
    _line(msp, tip, land)
    _arrow(msp, tip, land)
    x, y_mid = d.text_at
    lines = d.text.split("\n")
    first_w = 0.0
    for k, line in enumerate(lines):
        base = y_mid - TEXT_H / 2 - k * TEXT_H * 1.6
        if k == 0 and d.tolerance is not None:
            m = next((m for rx in _VALUE if (m := rx.search(line))), None)
            head, tail = (line[: m.end()], line[m.end():]) if m else (line, "")
            pieces, w, _ = label_pieces(head, d.tolerance)
            pieces.append((tail, w, 0.0, TEXT_H))
            _place(msp, pieces, (x, base), 0.0)
            first_w = w + text_w(tail, TEXT_H)
        else:
            _text(msp, line, (x, base), TEXT_H, "DIM")
            if k == 0:
                first_w = text_w(line, TEXT_H)
    if d.inspection:
        h = (2 * TOL_H + 0.5) if d.tolerance is not None and d.tolerance.kind != "SYMMETRIC" else TEXT_H
        _stadium(msp, -1.5, -1.0, first_w + 1.5, h + 1.0, origin=(x, y_mid - TEXT_H / 2))


# ---------------------------------------------------------------------------- GD&T

def _gdt_symbol(msp, name: str, cx: float, cy: float, s: float = 4.0, layer="GDT") -> None:
    """Vector geometric-characteristic symbols (ISO 1101 / ASME Y14.5 shapes)."""
    h = s / 2

    def ln(a, b):
        _line(msp, (cx + a[0], cy + a[1]), (cx + b[0], cy + b[1]), layer)

    if name == "STRAIGHTNESS":
        ln((-h, 0), (h, 0))
    elif name == "FLATNESS":
        pts = [(-h, -h * 0.5), (h * 0.5, -h * 0.5), (h, h * 0.5), (-h * 0.5, h * 0.5)]
        msp.add_lwpolyline([(cx + x, cy + y) for x, y in pts], close=True, dxfattribs={"layer": layer})
    elif name == "CIRCULARITY":
        msp.add_circle((cx, cy), h * 0.8, dxfattribs={"layer": layer})
    elif name == "CYLINDRICITY":
        r = h * 0.6
        msp.add_circle((cx, cy), r, dxfattribs={"layer": layer})
        ln((-h * 0.9, -r), (-h * 0.2 - 0.35 * r, r * 1.4))
        ln((h * 0.2 + 0.35 * r, -r * 1.4), (h * 0.9, r))
    elif name in ("PROFILE_OF_A_LINE", "PROFILE_OF_A_SURFACE"):
        msp.add_arc((cx, cy - h * 0.4), h * 0.85, 0, 180, dxfattribs={"layer": layer})
        if name == "PROFILE_OF_A_SURFACE":
            ln((-h * 0.85, -h * 0.4), (h * 0.85, -h * 0.4))
    elif name == "ANGULARITY":
        ln((-h, -h * 0.7), (h, -h * 0.7))
        ln((-h, -h * 0.7), (h * 0.8, h * 0.7))
    elif name == "PERPENDICULARITY":
        ln((-h, -h * 0.7), (h, -h * 0.7))
        ln((0, -h * 0.7), (0, h * 0.9))
    elif name == "PARALLELISM":
        ln((-h * 0.8, -h * 0.8), (-h * 0.1, h * 0.8))
        ln((h * 0.1, -h * 0.8), (h * 0.8, h * 0.8))
    elif name == "POSITION":
        msp.add_circle((cx, cy), h * 0.6, dxfattribs={"layer": layer})
        ln((-h, 0), (h, 0))
        ln((0, -h), (0, h))
    elif name == "CONCENTRICITY":
        msp.add_circle((cx, cy), h * 0.85, dxfattribs={"layer": layer})
        msp.add_circle((cx, cy), h * 0.45, dxfattribs={"layer": layer})
    elif name == "SYMMETRY":
        ln((-h * 0.55, h * 0.55), (h * 0.55, h * 0.55))
        ln((-h, 0), (h, 0))
        ln((-h * 0.55, -h * 0.55), (h * 0.55, -h * 0.55))
    elif name in ("CIRCULAR_RUNOUT", "TOTAL_RUNOUT"):
        tips = [(-h * 0.1, h)] if name == "CIRCULAR_RUNOUT" else [(-h * 0.45, h), (h * 0.55, h)]
        for tx, ty in tips:
            bx, by = tx - h * 0.5, -h * 0.8
            ln((bx, by), (tx, ty))
            _arrow(msp, (cx + tx, cy + ty), (cx + bx, cy + by), size=1.6, layer=layer)
        if name == "TOTAL_RUNOUT":
            ln((-h * 0.95, -h * 0.8), (h * 0.05, -h * 0.8))


def _frames(msp, frames: list[FrameSpec], origin) -> None:
    x0, top = origin
    for k, fr in enumerate(frames):
        y1 = top - k * fr.height
        y0 = y1 - fr.height
        cy = (y0 + y1) / 2
        x = x0
        for cell in fr.cells:
            _rect(msp, Rect(x0=x, y0=y0, x1=x + cell.width, y1=y1), "GDT")
            cx = x + cell.width / 2
            if cell.symbol:
                _gdt_symbol(msp, cell.symbol, cx, cy)
            else:
                parts_w = (text_w("Ø", TEXT_H) + 0.3 if cell.diameter else 0.0) + text_w(cell.text or "", TEXT_H) + (
                    4.0 if cell.modifier else 0.0)
                u = cx - parts_w / 2
                if cell.diameter:
                    _text(msp, "Ø", (u, cy), TEXT_H, "GDT", "ML")
                    u += text_w("Ø", TEXT_H) + 0.3
                _text(msp, cell.text or "", (u, cy), TEXT_H, "GDT", "ML")
                u += text_w(cell.text or "", TEXT_H)
                if cell.modifier:
                    _circled(msp, cell.modifier[0], u + 2.1, cy)
            x += cell.width


def _datum_box(msp, box: Rect, letter: str) -> None:
    _rect(msp, box, "GDT")
    _text(msp, letter, ((box.x0 + box.x1) / 2, (box.y0 + box.y1) / 2), TEXT_H, "GDT", "MC")


def _datum_symbol(msp, line, box: Rect, letter: str) -> None:
    """Datum feature symbol: filled triangle on the feature, connecting line, boxed letter."""
    apex = _triangle(msp, line[0], line[-1])
    _line(msp, apex, line[-1], "GDT")
    _datum_box(msp, box, letter)


def _dim_pmi(msp, d: DimensionOp) -> None:
    if d.frames and d.frames_origin:
        _frames(msp, d.frames, d.frames_origin)
    if d.datum and d.datum_box and len(d.datum_line) >= 2:
        _datum_symbol(msp, d.datum_line, d.datum_box, d.datum)


def _surface_finish(msp, p: PmiOp) -> None:
    """ISO 1302 basic surface texture symbol (no process requirement) with the Ra value."""
    if len(p.leader) >= 2:
        _line(msp, p.leader[0], p.leader[-1], "GDT")
        _arrow(msp, p.leader[0], p.leader[-1], layer="GDT")
    up = p.direction
    right = (up[1], -up[0])
    if right[0] < -1e-9 or (abs(right[0]) < 1e-9 and right[1] < 0):
        right = (-right[0], -right[1])  # keep the text readable

    def at(u, v):
        return (p.tip[0] + right[0] * u + up[0] * v, p.tip[1] + right[1] * u + up[1] * v)

    h1 = 5.0
    t60 = math.tan(math.radians(60))
    _line(msp, at(0, 0), at(-h1 / t60, h1), "GDT")
    _line(msp, at(0, 0), at(2 * h1 / t60, 2 * h1), "GDT")
    text = p.text or ""
    tw = text_w(text, TOL_H)
    _line(msp, at(2 * h1 / t60, 2 * h1), at(2 * h1 / t60 + tw + 1.5, 2 * h1), "GDT")
    rot = math.degrees(math.atan2(right[1], right[0]))
    _text(msp, text, at(2 * h1 / t60 + 0.8, 2 * h1 - TOL_H - 0.8), TOL_H, "GDT", "L", rot)


def _pmi(msp, p: PmiOp) -> None:
    if p.kind == PmiKind.SURFACE_FINISH:
        _surface_finish(msp, p)
        return
    tip, land = p.leader[0], p.leader[-1]
    if p.frames:
        _line(msp, tip, land, "GDT")
        _arrow(msp, tip, land, layer="GDT")
        _frames(msp, p.frames, p.frames_origin)
        if p.datum and p.datum_box:
            # datum feature symbol attached to the frame (it identifies the same face)
            cx = (p.datum_box.x0 + p.datum_box.x1) / 2
            frames_bottom = p.frames_origin[1] - sum(f.height for f in p.frames)
            _datum_symbol(msp, [(cx, frames_bottom), (cx, p.datum_box.y1)], p.datum_box, p.datum)
    elif p.datum and p.datum_box:
        _datum_symbol(msp, [tip, land], p.datum_box, p.datum)


# ---------------------------------------------------------------------------- sheet format

def _zones(msp, cd: CompiledDrawing) -> None:
    """ISO 5457 grid reference: columns numbered right-to-left, rows lettered bottom-to-top."""
    f = cd.frame
    cols, rows = cd.zones
    cw, rh = f.w / cols, f.h / rows
    m_x, m_y = f.x0, f.y0  # margin widths
    for i in range(1, cols):
        x = f.x0 + i * cw
        _line(msp, (x, f.y1), (x, f.y1 + m_y / 2), "ZONES")
        _line(msp, (x, f.y0), (x, f.y0 - m_y / 2), "ZONES")
    for j in range(1, rows):
        y = f.y0 + j * rh
        _line(msp, (f.x0, y), (f.x0 - m_x / 2, y), "ZONES")
        _line(msp, (f.x1, y), (f.x1 + m_x / 2, y), "ZONES")
    h = 3.5
    for i in range(cols):
        label = str(cols - i)
        x = f.x0 + (i + 0.5) * cw
        _text(msp, label, (x, f.y1 + m_y / 2), h, "ZONES", "MC")
        _text(msp, label, (x, f.y0 - m_y / 2), h, "ZONES", "MC")
    for j in range(rows):
        label = chr(ord("A") + j) if j < 8 else chr(ord("A") + j + 1)  # skip I
        y = f.y0 + (j + 0.5) * rh
        _text(msp, label, (f.x0 - m_x / 2, y), h, "ZONES", "MC")
        _text(msp, label, (f.x1 + m_x / 2, y), h, "ZONES", "MC")


def _projection_symbol(msp, cx: float, cy: float, third_angle: bool, s: float = 1.0) -> None:
    """ISO 128 / ISO 5456-2 projection symbol: truncated cone (side view) + end view circles.

    The end view shows the cone from its small end. In first-angle projection that view is placed
    on the side of the large end (circles right of the trapezoid); in third angle on the side of
    the small end (circles left)."""
    D, d, L, gap = 8.0 * s, 4.0 * s, 9.0 * s, 4.0 * s
    total = L + gap + D
    x0 = cx - total / 2
    if third_angle:
        c_x, t0 = x0 + D / 2, x0 + D + gap  # circles left, trapezoid right (small end left)
        small_x, large_x = t0, t0 + L
    else:
        t0 = x0  # trapezoid left (small end left), circles right
        small_x, large_x = t0, t0 + L
        c_x = x0 + L + gap + D / 2
    msp.add_lwpolyline([(small_x, cy - d / 2), (large_x, cy - D / 2), (large_x, cy + D / 2), (small_x, cy + d / 2)],
                       close=True, dxfattribs={"layer": "TITLE"})
    msp.add_circle((c_x, cy), D / 2, dxfattribs={"layer": "TITLE"})
    msp.add_circle((c_x, cy), d / 2, dxfattribs={"layer": "TITLE"})
    _line(msp, (x0 - 1.5, cy), (x0 + total + 1.5, cy), "CENTER")
    _line(msp, (c_x, cy - D / 2 - 1.5), (c_x, cy + D / 2 + 1.5), "CENTER")


# title block grid (mm from the block's bottom-left corner; 180 x 55 standard template)
_TB_W, _TB_H = 180.0, 55.0
_SIGN_ROWS = [("", 33.9, 38.2), ("DRAWN", 29.5, 33.9), ("CHK'D", 25.4, 29.5), ("APPV'D", 21.3, 25.4),
              ("MFG", 16.9, 21.3), ("Q.A", 12.6, 16.9)]
_SIGN_COLS = (0.0, 10.0, 27.3, 44.6, 54.5)
_TB_LINES = [
    # horizontal (y, x_from, x_to)
    ("h", 38.2, 0.0, 180.0), ("h", 48.9, 98.8, 180.0), ("h", 17.3, 98.8, 180.0), ("h", 4.3, 54.5, 180.0),
    ("h", 16.9, 54.5, 98.8),
    *[("h", y0, 0.0, 54.5) for _, y0, _ in _SIGN_ROWS],
    # vertical (x, y_from, y_to)
    ("v", 33.9, 38.2, 55.0), ("v", 80.5, 38.2, 55.0), ("v", 98.8, 0.0, 55.0), ("v", 150.5, 48.9, 55.0),
    ("v", 54.5, 0.0, 38.2), ("v", 10.0, 12.6, 38.2), ("v", 27.3, 12.6, 38.2), ("v", 44.6, 12.6, 38.2),
    ("v", 166.8, 4.3, 17.3), ("v", 143.0, 0.0, 4.3),
]


def _title_block(msp, cd: CompiledDrawing, generator: str) -> None:
    tb = cd.title_block
    F = {f.label: f.value for f in cd.title_fields}
    sx = tb.w / _TB_W
    sy = tb.h / _TB_H

    def P(x, y):
        return (tb.x0 + x * sx, tb.y0 + y * sy)

    def label(text, x, y_top, h=1.8):
        _text(msp, text, P(x + 1.0, y_top - 1.0 - h), h, "TITLE")

    def value(text, x0, x1, y0, y1, h, align="MC", h_min=1.2):
        text, h = _fit(text, (x1 - x0) * sx - 2.0, h, h_min)
        if align == "MC":
            _text(msp, text, P((x0 + x1) / 2, (y0 + y1) / 2), h, "TITLE", "MC")
        else:
            _text(msp, text, P(x0 + 1.0, (y0 + y1) / 2), h, "TITLE", "ML")

    _rect(msp, tb, "FRAME")
    for kind, a, b, c in _TB_LINES:
        if kind == "h":
            _line(msp, P(b, a), P(c, a), "TITLE")
        else:
            _line(msp, P(a, b), P(a, c), "TITLE")

    # UNLESS OTHERWISE SPECIFIED block (general requirements - values only when supplied)
    block = [
        "UNLESS OTHERWISE SPECIFIED:",
        "DIMENSIONS ARE IN MILLIMETERS",
        f"SURFACE FINISH: {F.get('SURFACE_FINISH', 'UNSPECIFIED')}",
        "TOLERANCES:",
        f"   LINEAR: {F.get('LINEAR_TOL', 'UNSPECIFIED')}",
        f"   ANGULAR: {F.get('ANGULAR_TOL', 'UNSPECIFIED')}",
    ]
    y = 55.0 - 0.6
    for line in block:
        t, h = _fit(line, 33.9 * sx - 2.0, 1.5, 0.9)
        y -= 2.6
        _text(msp, t, P(1.0, y), h, "TITLE")
    label("FINISH:", 33.9, 55.0)
    value(F.get("FINISH", ""), 33.9, 80.5, 38.2, 49.0, 2.5)
    edges = F.get("EDGES", "")
    if edges:
        lines = edges.split("\n")
        for k, line in enumerate(lines):
            t, h = _fit(line, 18.3 * sx - 2.0, 1.8)
            _text(msp, t, P(89.65, 52.0 - k * 3.0), h, "TITLE", "MC")
    value("DO NOT SCALE DRAWING", 98.8, 150.5, 48.9, 55.0, 2.5)
    label("REVISION", 150.5, 55.0, 1.5)
    value(F.get("REVISION", ""), 162.0, 180.0, 48.9, 55.0, 3.0)
    value(F.get("ORGANIZATION", ""), 98.8, 180.0, 38.2, 48.9, 3.5)

    # sign-off table
    for name, (a, b) in zip(("NAME", "SIGNATURE", "DATE"), zip(_SIGN_COLS[1:], _SIGN_COLS[2:])):
        value(name, a, b, 33.9, 38.2, 1.8)
    for role, y0, y1 in _SIGN_ROWS[1:]:
        value(role, 0.0, 10.0, y0, y1, 1.6, "ML")
        key = {"DRAWN": "DRAWN", "CHK'D": "CHECKED", "APPV'D": "APPROVED", "MFG": "MFG", "Q.A": "QA"}[role]
        value(F.get(f"{key}_NAME", ""), 10.0, 27.3, y0, y1, 1.8, "ML")
        value(F.get(f"{key}_DATE", ""), 44.6, 54.5, y0, y1, 1.6, "ML", 0.9)

    # projection symbol + drawing standard
    third = F.get("PROJECTION", "FIRST_ANGLE").upper().startswith("THIRD")
    _projection_symbol(msp, *P(76.65, 31.0), third)
    value(("THIRD" if third else "FIRST") + " ANGLE PROJECTION", 54.5, 98.8, 22.5, 25.5, 1.8)
    extra = [f"{F.get('TYPE', '')}  ·  STANDARD: {F.get('STANDARD', '')}"]
    if F.get("PART_NO") and F.get("PART_NO") != F.get("DWG_NO"):
        extra.append(f"PART NO.: {F['PART_NO']}")
    if F.get("QTY"):
        extra.append(f"QTY: {F['QTY']}")
    for k, line in enumerate(extra[:2]):
        value(line, 54.5, 98.8, 19.6 - k * 2.7, 21.6 - k * 2.7, 1.6)

    label("MATERIAL:", 54.5, 16.9)
    value(F.get("MATERIAL", ""), 54.5, 98.8, 4.3, 13.0, 3.5)
    t, h = _fit(f"WEIGHT: {F.get('WEIGHT', '')}", 44.3 * sx - 2.0, 1.8)
    _text(msp, t, P(55.5, 2.15), h, "TITLE", "ML")
    label("TITLE:", 98.8, 38.2)
    value(F.get("TITLE", ""), 98.8, 180.0, 17.3, 34.5, 5.0, h_min=2.5)
    label("DWG NO.", 98.8, 17.3)
    value(F.get("DWG_NO", ""), 98.8, 166.8, 4.3, 13.5, 3.5)
    value(F.get("SHEET_SIZE", ""), 166.8, 180.0, 4.3, 17.3, 5.0)
    t, h = _fit(f"SCALE: {F.get('SCALE', '')}", 44.2 * sx - 2.0, 1.8)
    _text(msp, t, P(99.8, 2.15), h, "TITLE", "ML")
    t, h = _fit(f"SHEET {F.get('SHEET', '1 OF 1')}", 37.0 * sx - 2.0, 1.8)
    _text(msp, t, P(144.0, 2.15), h, "TITLE", "ML")

    # provenance (kept inside the title block - never presented as SolidWorks output)
    prov = _wrap(PROVENANCE, 52) + [f"EXECUTOR: {generator}", f"DATE: {F.get('DATE', '')}"]
    for k, line in enumerate(prov[:4]):
        t, h = _fit(line, 54.5 * sx - 2.0, 1.2, 0.7)
        _text(msp, t, P(1.0, 10.4 - k * 2.6), h, "TITLE")


def _wrap(text: str, n: int) -> list[str]:
    out, cur = [], ""
    for w in text.split():
        if cur and len(cur) + 1 + len(w) > n:
            out.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    return out + ([cur] if cur else [])


def _sheet_notes(msp, cd: CompiledDrawing) -> None:
    if not cd.sheet_notes or cd.notes_rect is None:
        return
    r = cd.notes_rect
    y = r.y1 - 1.0 - 3.0
    _text(msp, "Note:", (r.x0 + 1.0, y), 3.0, "NOTES")
    for line in cd.sheet_notes:
        y -= 5.0
        t, h = _fit(line, r.w - 8.0, 3.0, 2.0)
        _text(msp, t, (r.x0 + 6.0, y), h, "NOTES")


def _revision_table(msp, cd: CompiledDrawing) -> None:
    if not cd.revision_rows or cd.revision_rect is None:
        return
    r = cd.revision_rect
    rh = r.h / (len(cd.revision_rows) + 2)
    cols = [r.x0, r.x0 + 0.1 * r.w, r.x0 + 0.6 * r.w, r.x0 + 0.8 * r.w, r.x1]
    _rect(msp, r, "FRAME")
    for k in range(1, len(cd.revision_rows) + 2):
        _line(msp, (r.x0, r.y1 - k * rh), (r.x1, r.y1 - k * rh), "TITLE")
    for x in cols[1:-1]:
        _line(msp, (x, r.y0), (x, r.y1 - rh), "TITLE")
    _text(msp, "REVISIONS", ((r.x0 + r.x1) / 2, r.y1 - rh / 2), 2.5, "TITLE", "MC")
    rows = [["REV.", "DESCRIPTION", "DATE", "APPROVED"], *cd.revision_rows]
    for i, row in enumerate(rows):
        yc = r.y1 - (i + 1.5) * rh
        for j, cell in enumerate(row):
            t, h = _fit(cell, cols[j + 1] - cols[j] - 2.0, 2.5 if i else 2.0)
            _text(msp, t, ((cols[j] + cols[j + 1]) / 2, yc), h, "TITLE", "MC")


# ---------------------------------------------------------------------------- entry point

def write_dxf(cd: CompiledDrawing, sheet_lines: dict[str, dict], snapped: dict[str, tuple], path,
              generator: str, shading: dict[str, list] | None = None) -> None:
    """sheet_lines: view id -> {"visible": [...], "hidden": [...]} in sheet mm.
    snapped: dimension id -> (p1, p2) extension origins after snapping.
    shading: view id -> [(triangle points in sheet mm, shade 0..1)] drawn far-to-near (optional)."""
    doc = ezdxf.new("R2018", setup=True)
    _setup(doc)
    msp = doc.modelspace()
    _rect(msp, Rect(x0=0, y0=0, x1=cd.sheet_w, y1=cd.sheet_h), "SHEET")
    _rect(msp, cd.frame, "FRAME")
    _zones(msp, cd)
    for view in cd.views:
        for pts, shade in (shading or {}).get(view.id, []):
            g = int(round(150 + 95 * shade))
            msp.add_solid([pts[0], pts[1], pts[2]],
                          dxfattribs={"layer": "SHADE", "true_color": ezdxf.colors.rgb2int((g - 8, g - 4, g))})
        lines = sheet_lines[view.id]
        for layer in ("hidden", "visible"):
            for pl in lines[layer]:
                if len(pl) == 2:
                    msp.add_line(pl[0], pl[1], dxfattribs={"layer": layer.upper()})
                else:
                    msp.add_lwpolyline(pl, dxfattribs={"layer": layer.upper()})
    for a in cd.annotations:
        if a.kind == AnnotationKind.PITCH_CIRCLE:
            msp.add_circle(a.center, a.radius, dxfattribs={"layer": "CENTER"})
        elif a.kind == AnnotationKind.CENTER_MARK:
            p = a.points
            _line(msp, p[0], p[1], "CENTER")
            _line(msp, p[2], p[3], "CENTER")
        else:
            _line(msp, a.points[0], a.points[1], "CENTER")
    for d in cd.dimensions:
        if d.kind == DimensionOpKind.LINEAR:
            p1, p2 = snapped.get(d.id, (d.p1, d.p2))
            _linear(msp, d, p1, p2)
        else:
            _leader(msp, d)
        _dim_pmi(msp, d)
    for p in cd.pmi:
        _pmi(msp, p)
    _title_block(msp, cd, generator)
    _sheet_notes(msp, cd)
    _revision_table(msp, cd)
    doc.saveas(str(path))
