// Generate TypeScript types from the exported JSON Schemas (single source of truth: Pydantic).
import { compileFromFile } from "json-schema-to-typescript";
import { writeFile } from "node:fs/promises";

const root = new URL("../../../", import.meta.url);
const targets = [
  ["packages/geometry-schema/schema/geometry-ir.schema.json", "src/generated/geometry-ir.ts"],
  ["packages/drawing-schema/schema/drawing-plan.schema.json", "src/generated/drawing-plan.ts"],
  ["packages/drawing-schema/schema/drawing-settings.schema.json", "src/generated/drawing-settings.ts"],
  ["packages/drawing-schema/schema/qa-report.schema.json", "src/generated/qa-report.ts"],
];
const banner = "/* eslint-disable */\n// AUTO-GENERATED by `npm run gen:types` from the Pydantic JSON Schemas. Do not edit.\n";
for (const [src, dst] of targets) {
  const ts = await compileFromFile(new URL(src, root).pathname, {
    bannerComment: banner,
    additionalProperties: false,
    unreachableDefinitions: true,
    style: { singleQuote: false },
  });
  await writeFile(new URL(`../${dst}`, import.meta.url), ts);
  console.log(`wrote ${dst}`);
}
